$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
Set-Location $repoRoot

Write-Host "RAGPilot release commands" -ForegroundColor Cyan
Write-Host ""
Write-Host "1. Check current release state"
Write-Host "   npm run release:status"
Write-Host "   (checks unified preflight wiring, internal-doc exclusion, and validation-script presence)"
Write-Host ""
Write-Host "2. Run release validation"
Write-Host "   npm run release:preflight"
Write-Host ""
Write-Host "3. Audit the public documentation layer"
Write-Host "   npm run release:docs-audit"
Write-Host ""
Write-Host "4. Audit public markdown links"
Write-Host "   npm run release:links-audit"
Write-Host ""
Write-Host "5. Audit the public candidate file set"
Write-Host "   npm run release:candidate-audit"
Write-Host ""
Write-Host "6. Audit production delivery assets"
Write-Host "   npm run release:delivery-audit"
Write-Host ""
Write-Host "7. Run local CI checks"
Write-Host "   npm run release:ci-local"
Write-Host ""
Write-Host "8. Create the first baseline commit"
Write-Host "   npm run release:baseline-commit"
Write-Host ""
Write-Host "8b. Create a local-only baseline commit before LICENSE is chosen"
Write-Host "   npm run release:baseline-commit-local"
Write-Host ""
Write-Host "9. Configure the public remote"
Write-Host "   powershell -NoProfile -ExecutionPolicy Bypass -File infra/scripts/configure-remote.ps1 -RemoteUrl <your-github-repository-url>"
Write-Host ""
Write-Host "10. Push the default branch"
Write-Host "   npm run release:first-push"
Write-Host "   (override branch when needed: powershell ...\\push-first-public.ps1 -Branch <branch-name>)"
Write-Host ""
Write-Host "11. Create the first public tag"
Write-Host "   npm run release:first-tag"
Write-Host "   (validates release tags like v0.1.0 and can accept -Branch <branch-name>)"
Write-Host ""
Write-Host "12. Use the promotion helper when you want one entry point"
Write-Host "   npm run release:promote"
Write-Host "   (now runs release:status first and accepts -Branch / -Tag overrides)"
Write-Host ""
Write-Host "Current expected blockers before the first public push:" -ForegroundColor Cyan
Write-Host "- root public documentation audit"
Write-Host "- root public markdown link audit"
Write-Host "- production delivery audit"
Write-Host "- local CI checks"
Write-Host "- first baseline commit"
Write-Host "- configured Git remote"
